[compiler.solc]
exclude_paths = ["script", "lib", "test", "venv", ".venv", "node_modules"]
include_paths = ["node_modules"]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["venv", "test", ".venv"]
exclude_paths = ["script", "lib", "test", "venv", ".venv", "node_modules"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""